import './globals.css'
import type { Metadata } from 'next'
import Header from './components/header'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja"  className='h-screen w-screen'>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
